spring.application.name=artesanias-chigorodo

# Database configuration (H2 In-Memory)
spring.datasource.url=jdbc:h2:mem:artesanias_chigorodo;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# JWT Configurations
security.jwt.secret-key=${SECURITY_JWT_SECRET_KEY:YXJ0ZXNhbmlhc2NoaWdvcm9kb3NlY3JldGtleWZvcmp3dHRva2VuZ2VuZXJhdGlvbjIwMjY=}
security.jwt.expiration-time=${SECURITY_JWT_EXPIRATION_TIME:86400000}

# MongoDB Configuration
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/artesanias_chigorodo}
